package com.turing.entity;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_inmony
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String goodsInmony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_outmony
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String goodsOutmony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_intime
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Date goodsIntime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_outtime
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Date goodsOuttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_img
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String goodsImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_id
     *
     * @return the value of goods.goods_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_id
     *
     * @param goodsId the value for goods.goods_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goodsName the value for goods.goods_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_inmony
     *
     * @return the value of goods.goods_inmony
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getGoodsInmony() {
        return goodsInmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_inmony
     *
     * @param goodsInmony the value for goods.goods_inmony
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsInmony(String goodsInmony) {
        this.goodsInmony = goodsInmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_outmony
     *
     * @return the value of goods.goods_outmony
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getGoodsOutmony() {
        return goodsOutmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_outmony
     *
     * @param goodsOutmony the value for goods.goods_outmony
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsOutmony(String goodsOutmony) {
        this.goodsOutmony = goodsOutmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_intime
     *
     * @return the value of goods.goods_intime
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Date getGoodsIntime() {
        return goodsIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_intime
     *
     * @param goodsIntime the value for goods.goods_intime
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsIntime(Date goodsIntime) {
        this.goodsIntime = goodsIntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_outtime
     *
     * @return the value of goods.goods_outtime
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Date getGoodsOuttime() {
        return goodsOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_outtime
     *
     * @param goodsOuttime the value for goods.goods_outtime
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsOuttime(Date goodsOuttime) {
        this.goodsOuttime = goodsOuttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_img
     *
     * @return the value of goods.goods_img
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_img
     *
     * @param goodsImg the value for goods.goods_img
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }
}