package com.turing.entity;

public class Kaoqin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.kaoqin_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Integer kaoqinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.person_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaoqin.person_test
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personTest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.kaoqin_id
     *
     * @return the value of kaoqin.kaoqin_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Integer getKaoqinId() {
        return kaoqinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.kaoqin_id
     *
     * @param kaoqinId the value for kaoqin.kaoqin_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setKaoqinId(Integer kaoqinId) {
        this.kaoqinId = kaoqinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.person_id
     *
     * @return the value of kaoqin.person_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.person_id
     *
     * @param personId the value for kaoqin.person_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaoqin.person_test
     *
     * @return the value of kaoqin.person_test
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonTest() {
        return personTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaoqin.person_test
     *
     * @param personTest the value for kaoqin.person_test
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonTest(String personTest) {
        this.personTest = personTest;
    }
}