package com.turing.entity;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_role
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_edpt
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personEdpt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_gongzi
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personGongzi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_phone
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_email
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_qq
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String personQq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_id
     *
     * @return the value of person.person_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_id
     *
     * @param personId the value for person.person_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_name
     *
     * @return the value of person.person_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_name
     *
     * @param personName the value for person.person_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_role
     *
     * @return the value of person.person_role
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonRole() {
        return personRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_role
     *
     * @param personRole the value for person.person_role
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonRole(String personRole) {
        this.personRole = personRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_edpt
     *
     * @return the value of person.person_edpt
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonEdpt() {
        return personEdpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_edpt
     *
     * @param personEdpt the value for person.person_edpt
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonEdpt(String personEdpt) {
        this.personEdpt = personEdpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_gongzi
     *
     * @return the value of person.person_gongzi
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonGongzi() {
        return personGongzi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_gongzi
     *
     * @param personGongzi the value for person.person_gongzi
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonGongzi(String personGongzi) {
        this.personGongzi = personGongzi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_phone
     *
     * @return the value of person.person_phone
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonPhone() {
        return personPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_phone
     *
     * @param personPhone the value for person.person_phone
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonPhone(String personPhone) {
        this.personPhone = personPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_email
     *
     * @return the value of person.person_email
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonEmail() {
        return personEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_email
     *
     * @param personEmail the value for person.person_email
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonEmail(String personEmail) {
        this.personEmail = personEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_qq
     *
     * @return the value of person.person_qq
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getPersonQq() {
        return personQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_qq
     *
     * @param personQq the value for person.person_qq
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setPersonQq(String personQq) {
        this.personQq = personQq;
    }
}