package com.turing.entity;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_role
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pass
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    private String userEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_role
     *
     * @return the value of user.user_role
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_role
     *
     * @param userRole the value for user.user_role
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pass
     *
     * @return the value of user.user_pass
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pass
     *
     * @param userPass the value for user.user_pass
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
}