package com.turing.mapper;

import com.turing.entity.Goods;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    int insertSelective(Goods record);
}