package com.turing.mapper;

import com.turing.entity.Kaoqin;

public interface KaoqinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    int insert(Kaoqin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kaoqin
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    int insertSelective(Kaoqin record);
}