package com.turing.mapper;

import org.apache.ibatis.annotations.Select;

import com.turing.entity.UserEntity;


public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Sep 14 16:12:36 CST 2016
     */
    int insertSelective(UserEntity record);

    
    /**
     * 用户登陆查询
     * @param u
     * @return
     */
	UserEntity LoginQuery(UserEntity u);
}